/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vendingmachine;

import javax.swing.JOptionPane;

/**
 *
 * @author Boo
 */
public class MainVM extends javax.swing.JFrame {

    /**
     * Creates new form MainVM
     */
    public MainVM() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BeerRB = new javax.swing.JRadioButton();
        ColaRB = new javax.swing.JRadioButton();
        ChipsRB = new javax.swing.JRadioButton();
        NutsRB = new javax.swing.JRadioButton();
        WaterRB = new javax.swing.JRadioButton();
        ChocolateRB = new javax.swing.JRadioButton();
        PurchaseBtn = new javax.swing.JButton();
        ClearBtn = new javax.swing.JButton();
        CloseBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        InsertMoneyTF = new javax.swing.JTextField();
        ChangeTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Vending Machine");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Select an item"));

        BeerRB.setText("Beer 5.2 lei");
        BeerRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeerRBActionPerformed(evt);
            }
        });

        ColaRB.setText("Cola 3 lei");
        ColaRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColaRBActionPerformed(evt);
            }
        });

        ChipsRB.setText("Chips 3.5 lei");
        ChipsRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChipsRBActionPerformed(evt);
            }
        });

        NutsRB.setText("Nuts 2 lei");
        NutsRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NutsRBActionPerformed(evt);
            }
        });

        WaterRB.setText("Water 2.3 lei");
        WaterRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WaterRBActionPerformed(evt);
            }
        });

        ChocolateRB.setText("Chocolate 3.2 lei ");
        ChocolateRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChocolateRBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BeerRB)
                    .addComponent(ColaRB))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NutsRB)
                    .addComponent(ChipsRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChocolateRB)
                    .addComponent(WaterRB))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BeerRB)
                    .addComponent(ChipsRB)
                    .addComponent(WaterRB))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ColaRB)
                    .addComponent(NutsRB)
                    .addComponent(ChocolateRB))
                .addGap(20, 20, 20))
        );

        PurchaseBtn.setText("Purchase");
        PurchaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PurchaseBtnActionPerformed(evt);
            }
        });

        ClearBtn.setText("Clear");
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });

        CloseBtn.setText("Close");
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Inserted Money:");

        jLabel3.setText("Change :");

        InsertMoneyTF.setText(" ");
        InsertMoneyTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        InsertMoneyTF.setName(""); // NOI18N
        InsertMoneyTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertMoneyTFActionPerformed(evt);
            }
        });

        ChangeTF.setEditable(false);
        ChangeTF.setText(" ");
        ChangeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PurchaseBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ClearBtn)
                        .addGap(109, 109, 109)
                        .addComponent(CloseBtn))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(InsertMoneyTF)
                    .addComponent(ChangeTF, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(InsertMoneyTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ChangeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PurchaseBtn)
                    .addComponent(ClearBtn)
                    .addComponent(CloseBtn))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BeerRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeerRBActionPerformed
        // Select Beer
        if(BeerRB.isSelected()){ 
           ColaRB.setSelected(false);
           ChipsRB.setSelected(false);
           NutsRB.setSelected(false);
           WaterRB.setSelected(false);
           ChocolateRB.setSelected(false);
           }
            
    }//GEN-LAST:event_BeerRBActionPerformed

    private void ChipsRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChipsRBActionPerformed
        // TODO add your handling code here:
         if(ChipsRB.isSelected()){ 
           ColaRB.setSelected(false);
           BeerRB.setSelected(false);
           NutsRB.setSelected(false);
           WaterRB.setSelected(false);
           ChocolateRB.setSelected(false);
           }
    }//GEN-LAST:event_ChipsRBActionPerformed

    private void ColaRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColaRBActionPerformed
        // TODO add your handling code here:
        if(ColaRB.isSelected()){ 
           ChipsRB.setSelected(false);
           BeerRB.setSelected(false);
           NutsRB.setSelected(false);
           WaterRB.setSelected(false);
           ChocolateRB.setSelected(false);
           }
    }//GEN-LAST:event_ColaRBActionPerformed

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
        // Clear selected RB or inserted money
        
        BeerRB.setSelected(false);
        ColaRB.setSelected(false);
        ChipsRB.setSelected(false);
        NutsRB.setSelected(false);
        WaterRB.setSelected(false);
        ChocolateRB.setSelected(false);
        InsertMoneyTF.setEnabled(true);
        InsertMoneyTF.setText(" ");
        ChangeTF.setText(" ");
        money=0;
        
        
    }//GEN-LAST:event_ClearBtnActionPerformed

    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        // Close application
        System.exit(0);
    }//GEN-LAST:event_CloseBtnActionPerformed

    private void NutsRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NutsRBActionPerformed
        // TODO add your handling code here:
         if(NutsRB.isSelected()){ 
           ColaRB.setSelected(false);
           ChipsRB.setSelected(false);
           BeerRB.setSelected(false);
           WaterRB.setSelected(false);
           ChocolateRB.setSelected(false);
           }
    }//GEN-LAST:event_NutsRBActionPerformed

    private void WaterRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WaterRBActionPerformed
        // TODO add your handling code here:
         if(WaterRB.isSelected()){ 
           ColaRB.setSelected(false);
           ChipsRB.setSelected(false);
           BeerRB.setSelected(false);
           NutsRB.setSelected(false);
           ChocolateRB.setSelected(false);
           }
    }//GEN-LAST:event_WaterRBActionPerformed

    private void ChocolateRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChocolateRBActionPerformed
        // TODO add your handling code here:
        if(ChocolateRB.isSelected()){ 
           ColaRB.setSelected(false);
           ChipsRB.setSelected(false);
           BeerRB.setSelected(false);
           NutsRB.setSelected(false);
           WaterRB.setSelected(false);
           }
    }//GEN-LAST:event_ChocolateRBActionPerformed

    private void InsertMoneyTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertMoneyTFActionPerformed
        // TODO add your handling code here:
      if(InsertMoneyTF.isCursorSet())
        InsertMoneyTF.setText(" ");
    }//GEN-LAST:event_InsertMoneyTFActionPerformed

    private void ChangeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeTFActionPerformed
        // TODO add your handling code here:
        ChangeTF.setText("0");
    }//GEN-LAST:event_ChangeTFActionPerformed

    private void PurchaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurchaseBtnActionPerformed
        // TODO add your handling code here:
        somethingSelected=false;
        if(money==0){
             money = Float.parseFloat(InsertMoneyTF.getText());
             InsertMoneyTF.setEnabled(false);
        } 
        
        if(BeerRB.isSelected()&& money>=5.2f){
            money-=5.2f;
            BeerRB.setSelected(false);
        }
        else if(ColaRB.isSelected()&& money>=3.0f){
            money-=3.0f;
            ColaRB.setSelected(false);
        }
        else if(ChipsRB.isSelected()&& money>=3.5f){
            money-=3.5f;
            ChipsRB.setSelected(false);
        }
        else if(NutsRB.isSelected()&& money>=2.0f){
            money-=2.0f;
            NutsRB.setSelected(false);
        }
        else if(WaterRB.isSelected()&& money>=2.3f){
            money-=2.3f;
            WaterRB.setSelected(false);
        }
        else if(ChocolateRB.isSelected()&& money>=3.2f){
            money-=3.2f;
            ChocolateRB.setSelected(false);
        }
        else if(ChocolateRB.isSelected()==WaterRB.isSelected()==NutsRB.isSelected()==ChipsRB.isSelected()==ColaRB.isSelected()==BeerRB.isSelected()){
            JOptionPane.showMessageDialog(rootPane, "You didn't selected any item");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "You don't have enough money for this item");
        }
        
        ChangeTF.setText((String.format("%.1f",money)));
       
    }//GEN-LAST:event_PurchaseBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainVM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainVM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainVM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainVM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainVM().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BeerRB;
    private javax.swing.JTextField ChangeTF;
    private javax.swing.JRadioButton ChipsRB;
    private javax.swing.JRadioButton ChocolateRB;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JButton CloseBtn;
    private javax.swing.JRadioButton ColaRB;
    private javax.swing.JTextField InsertMoneyTF;
    private javax.swing.JRadioButton NutsRB;
    private javax.swing.JButton PurchaseBtn;
    private javax.swing.JRadioButton WaterRB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    float money=0;
    boolean somethingSelected=false;
}
